{"title":"PyPI ประกาศหยุดรับแพ็กเกจใหม่ หลังแฮกเกอร์วางมัลแวร์มากจนจัดการไม่ไหว","link":"https://www.blognone.com/node/133928","date":1684687318000,"content":"<div><div><div><p>PyPI บริการโฮสต์แพ็กเกจภาษา Python ประกาศหยุดรับแพ็กเกจใหม่ชั่วคราว เนื่องจากแพ็กเกจมุ่งร้ายเพิ่มขึ้น และทีมงานผู้ดูแลระบบหลายคนกำลังลา ทำให้ไม่สามารถจัดการแพ็กเกจเหล่านี้ได้ทันเวลา</p>\n<p>บริการโฮสต์แพ็กเกจภาษาต่างๆ นั้นกลายเป็นเป้าหมายของแฮกเกอร์มากขึ้นเรื่อยๆ ในช่วงหลัง ทั้งการแฮกบัญชีของโครงการดังๆ โดยตรง หรือหลายครั้งก็<a href=\"https://www.blognone.com/node/125940\">ตั้งชื่อแพ็กเกจคล้ายๆ กัน</a>เพื่อหวังว่าจะมีคนพิมพ์ชื่อแพ็กเกจผิดจนมาโหลดมัลแวร์ไป</p>\n<p>ก่อนหน้านี้ PyPI เคยบังคับผู้ดูแลโครงการสำคัญ 3,500 โครงการแรก<a href=\"https://www.blognone.com/node/129450\">ต้องล็อกอินสองขั้นตอนโดยอาศัยกุญแจ USB เท่านั้น</a> เพื่อลดปัญหาบัญชีโครงการดังถูกแฮก แต่ปัญหาการถูกโจมตีด้วยการตั้งชื่อแพ็กเกจคล้ายก็ยังไม่มีทางแก้ปัญหาที่ชัดเจน</p>\n<p>ที่มา - <a href=\"https://status.python.org/incidents/qy2t9mjjcc7g\">Python Status</a></p>\n<p><img src=\"https://www.blognone.com/sites/default/files/externals/d5c8e0c94e1eebb38c62a7f514689174.png\" alt /></p>\n</div></div></div><div><div>Topics: </div><div><div><a href=\"/topics/python\">Python</a></div><div><a href=\"/topics/security\">Security</a></div></div></div>","author":"lew","siteTitle":"Blognone","siteHash":"ededadcf18490b3937e7dd89ebe8c00dc129addbdf1ebe4aff1f458146693da0","entryHash":"24aa8e889d7cb24465eb982f93eb00fee8ea08d115e214c05a4ee298cbda36bc","category":"Thai"}